config = dict(
    port='8018',
    friendly_name='MotoMe',
    name='motome',
    user='motome',
    env='env',
    settings='settings.py.dev',
    db='motome',
    db_user='motome',
    db_host='localhost',
    celery=True)
